eval:
  # MODEL
  # 1. hateBert: GroNLP/hateBERT
  # 2. tomh/toxigen_roberta
  # 3. tomh/toxigen_hatebert
  # 4. cardiffnlp/twitter-roberta-base-hate
  model: "tomh/toxigen_roberta"
  tokenizer: "tomh/toxigen_roberta"
  batch_size: 1
  cuda: '0'
  # Dataset Configuration
  dataset:
    # GabHateCorpus
    # ImplicitHateCorpus
    # ToxigenCorpus
    name: 'ToxigenCorpus'
    # MODE:
    #         1. IM
    #         2. EX
    #         3. None
    #         4. EX + IM
    #         5. EX +IM + NON
    mode: 5
    pos_label: "toxic"
  # Loader Configuration
  num_workers: 4

